package jp.co.trainocamp.demo.mybatis.entity;

public class MybatisPlace {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MYBATIS_PLACE.ID
     *
     * @mbg.generated Thu May 25 14:15:09 JST 2023
     */
    private Integer placeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MYBATIS_PLACE.NAME
     *
     * @mbg.generated Thu May 25 14:15:09 JST 2023
     */
    private String placeName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MYBATIS_PLACE.ID
     *
     * @return the value of MYBATIS_PLACE.ID
     *
     * @mbg.generated Thu May 25 14:15:09 JST 2023
     */
    public Integer getId() {
        return placeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MYBATIS_PLACE.ID
     *
     * @param id the value for MYBATIS_PLACE.ID
     *
     * @mbg.generated Thu May 25 14:15:09 JST 2023
     */
    public void setId(Integer placeId) {
        this.placeId = placeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MYBATIS_PLACE.NAME
     *
     * @return the value of MYBATIS_PLACE.NAME
     *
     * @mbg.generated Thu May 25 14:15:09 JST 2023
     */
    public String getName() {
        return placeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MYBATIS_PLACE.NAME
     *
     * @param name the value for MYBATIS_PLACE.NAME
     *
     * @mbg.generated Thu May 25 14:15:09 JST 2023
     */
    public void setName(String placeName) {
        this.placeName = placeName == null ? null : placeName.trim();
    }
}