package jp.co.trainocamp.demo.mybatis.mapper;

import java.util.List;
import jp.co.trainocamp.demo.mybatis.entity.MybatisPlace;
import jp.co.trainocamp.demo.mybatis.entity.MybatisPlaceExample;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface MybatisPlaceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MYBATIS_PLACE
     *
     * @mbg.generated Thu May 25 14:15:09 JST 2023
     */
    long countByExample(MybatisPlaceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MYBATIS_PLACE
     *
     * @mbg.generated Thu May 25 14:15:09 JST 2023
     */
    int deleteByExample(MybatisPlaceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MYBATIS_PLACE
     *
     * @mbg.generated Thu May 25 14:15:09 JST 2023
     */
    int deleteByPrimaryKey(Integer placeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MYBATIS_PLACE
     *
     * @mbg.generated Thu May 25 14:15:09 JST 2023
     */
    int insert(MybatisPlace row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MYBATIS_PLACE
     *
     * @mbg.generated Thu May 25 14:15:09 JST 2023
     */
    int insertSelective(MybatisPlace row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MYBATIS_PLACE
     *
     * @mbg.generated Thu May 25 14:15:09 JST 2023
     */
    List<MybatisPlace> selectByExample(MybatisPlaceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MYBATIS_PLACE
     *
     * @mbg.generated Thu May 25 14:15:09 JST 2023
     */
    MybatisPlace selectByPrimaryKey(Integer placeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MYBATIS_PLACE
     *
     * @mbg.generated Thu May 25 14:15:09 JST 2023
     */
    int updateByExampleSelective(@Param("row") MybatisPlace row, @Param("example") MybatisPlaceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MYBATIS_PLACE
     *
     * @mbg.generated Thu May 25 14:15:09 JST 2023
     */
    int updateByExample(@Param("row") MybatisPlace row, @Param("example") MybatisPlaceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MYBATIS_PLACE
     *
     * @mbg.generated Thu May 25 14:15:09 JST 2023
     */
    int updateByPrimaryKeySelective(MybatisPlace row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MYBATIS_PLACE
     *
     * @mbg.generated Thu May 25 14:15:09 JST 2023
     */
    int updateByPrimaryKey(MybatisPlace row);

    List<MybatisPlace> selectAll();
}