INSERT INTO MYBATIS_USER (ID, NAME, AGE) VALUES (1, 'SATO TARO', 18);
INSERT INTO MYBATIS_USER (ID, NAME, AGE) VALUES (2, 'TAKAHASHI JIRO', 20);
INSERT INTO MYBATIS_USER (ID, NAME, AGE) VALUES (3, 'SUZUKI SABURO', 21);

INSERT INTO MYBATIS_PLACE (ID, NAME) VALUES (1, 'TOKYO');
INSERT INTO MYBATIS_PLACE (ID, NAME) VALUES (2, 'OSAKA');
INSERT INTO MYBATIS_PLACE (ID, NAME) VALUES (3, 'NAGOYA');