CREATE TABLE IF NOT EXISTS MYBATIS_USER (
	ID INT NOT NULL,
	NAME VARCHAR(50),
	AGE INT,
	PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS MYBATIS_PLACE (
	ID INT NOT NULL,
	NAME VARCHAR(50),
	PRIMARY KEY (ID)
);